### PR TITLE
Julian macro

### PR DESCRIPTION
**Pull request by mcabbott**
I had a go at #21, but see that while I had the tab open, you've added a string macro which works precisely the same way mine did. So this PR adds only the non-string macro, which should understand the same notation as TensorOperations.jl etc. 

It adds a dependency on MacroTools.jl but that's not heavy. 

The function `einsum!(`3 tuples`, Z)` seems to have vanished, so for now the in-place variant calls `einsumexp!`, and for now `@einopt` is omitted. 

Maybe the name `@ein` is too short, would be nice not to clash with anything though. Perhaps there should be `@ein_loops` etc, or an option afterwards `@ein A[i] := B[i] loops`?

Tests on nightly fail on "gradient type check" which I don't think is my fault.

### CODE REVIEW

**Comment by under-Peter** [comment]
Hi @mcabbott, thanks for your contribution!
I'll have to dive a bit into macros and `MacroTools` before I can properly review this PR but I'll try to do it soon.
Cheers

**Comment by mcabbott** [comment]
Sure, no rush. Let me know if you'd like changes to what this does. 
```
julia> @macroexpand @ein Z[i,j,k] := A[i,1] * B[1,j] * C[k]
:(Z = (OMEinsum.einsum)((OMEinsum.EinCode){((1, 2), (2, 3), (4,)), (1, 3, 4)}(), (A, B, C)))
```

**Comment by Roger-luo** [comment]
I'm wondering if we could use an alternative Julia Expr manipulation here: https://github.com/QuantumBFS/YaoBase.jl/blob/master/src/utils/ast_tools.jl

It should be much faster than MacroTools.jl with MLStyle.jl. I'm happy to put it in a package if you want. It is not possible to be a PR to MacroTools since they have different syntax (but similar tho).

**Comment by mcabbott** [comment]
Right now it takes just under 1ms, but only once, at parse-time. Can this be a bottleneck? 

It would be great anyway to have this alternative packaged up, though. Could such a package provide a drop-in replacement for `@capture`, perhaps in addition to this other macro one which returns a dict? The pattern `if @capture(ex, stuff_); use stuff; ...` is very neat, `ASTTools.@capture` seems instead to throw an error if it doesn't match. (I haven't understood whether the $ signs are necessary for speed, or a style choice.)

**Comment by Roger-luo** [comment]
I believe $ is more canonical. See detailed explanation here: https://discourse.julialang.org/t/static-capture-instead-of-that-of-macrotools-jl-more-efficient-more-functionalities-more-straightforward/20604?u=roger-luo

But yeah it is not a big deal.

**Comment by mcabbott** [comment]
Perhaps OT, but I put an attempt to package up a faster `@capture` in [this gist](https://gist.github.com/mcabbott/db51045cd5b59b99bb51b93881dae26b). It's a lot faster, if you work around various issues (avoiding capital letters, and `p | q` patterns): 
```
julia> @btime _ein_macro(:( Z[i,j,k] := A[i,1] * B[1,j] * C[k] ))  
  28.195 μs (228 allocations: 22.38 KiB)
```

**Comment by Roger-luo** [comment]
@thautwarm I thought the capital letter issue was solved? do you have time to revise the implementation a little bit (in YaoBase)?

**Comment by thautwarm** [comment]
@Roger-luo It's now an extension:
https://thautwarm.github.io/MLStyle.jl/latest/syntax/extension/#UppercaseCapturing-1

As we'll sync in July 16, we can revise it together that time.

**Pull request merged**
