### PR TITLE
use ZygoteRules

### PR DESCRIPTION
**Pull request by mcabbott**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Great, this will improve the user experience by an order :laughing:

**Comment by mcabbott** [comment]
I hope so! Any idea what might cause this error? 
```
ERROR: MethodError: no method matching getindex(::Nothing, ::String)
178Stacktrace:
179 [1] #build_versions#47(::Bool, ::Function, ::Pkg.Types.Context, ::Array{Base.UUID,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1044
180 [2] build_versions at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1033 [inlined]
181 [3] #instantiate#61(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:575
```
(Test fail locally, but for other reasons, even before PR.)

**Comment by GiggleLiu** [comment]
@mcabbott This error will probably be fixed by #80 
IThe tensor contraction backend `BatchedRoutines` does not support `FilledArrays`, it should be dispatched to the default implementation.

**Comment by GiggleLiu** [comment]
I merged #80 now, the test should be fixed. But I haven't check the performance yet.

## Warning:
In #80, I moved the contraction tree optimization in TO from static to dynamic, while the contraction is handled by batched routines now. This change will favor random graph contraction, but causes runtime overhead. In most cases, this is not the bottlenet of programs.

Do you have any opinions on this?

**Comment by GiggleLiu** [comment]
The test coverage is not executed, don't know why. I will merge it to master first.
```
$ export CI_DISABLE_CURNN_TEST=true
00:01
 $ julia -e 'using Pkg; Pkg.add("Coverage")'
 /bin/bash: line 97: julia: command not found
 ERROR: Job failed: exit code 1
```

**Comment by mcabbott** [comment]
Thanks! Glad it's working. 

No useful opinions on #80 I'm afraid.

**Pull request merged**
