### PR TITLE
WIP: Refactor for v0.2.0

### PR DESCRIPTION
**Pull request by GiggleLiu**
see #40 for a list of changes.

### CODE REVIEW

**Comment by under-Peter** [comment]
Can you please try the example from the OMEinsum-ReadMe?
That is:
```julia
julia> d = 5; χ = 50; a = randn(χ,χ); b= randn(χ,d,χ); c = randn(d,d,d,d);
julia> @time einsum(EinCode((('i','j'), ('i','k','l'), ('j','m','n'), ('k','m','o','p')), ('l','n','o','p')), (a, b, b, c));
```
I think ti should use `Pairwise` but might be using `Fallback` instead.

**Comment by GiggleLiu** [comment]
I got 57s, that is strange, since
```julia
julia> OMEinsum.match_rule((('i','j'), ('i','k','l'), ('j','m','n'), ('k','m','o','p')), ('l','n','o','p'))
OMEinsum.PairWise()
```

`@einsumopt` is slow? or maybe some stupid bug.

**Comment by under-Peter** [comment]
Even the second time it runs it takes on the order of 50s for me. Tensoropt might be slow but should only be once, at compiletime.

**Comment by GiggleLiu** [comment]
Yes, a stupid error in dispatch! I will fix this bug ASAP.
```julia
julia> @time einsum(EinCode((('i','j'), ('i','k','l'), ('j','m','n'), ('k','m','o','p')), ('l','n','o','p')), (a, b, b, c));
  0.005709 seconds (212 allocations: 500.641 KiB)
```

**Comment by under-Peter** [comment]
Since we have #42, can this be closed? @GiggleLiu

**Comment by GiggleLiu** [comment]
dup with #42.

**Pull request closed without merging**
