### PR TITLE
fix type instability

### PR DESCRIPTION
**Pull request by GiggleLiu**
It fixes the type instability issue in #92

### CODE REVIEW

**Comment by under-Peter** [comment]
I'm not sure what's happening here - do you know the source of the type stability as described in #92 ?

**Comment by GiggleLiu** [comment]
Hi, @under-Peter 
This is my fault, I changed some routines of analysing EinCode from compile stage to runtime in a version in order to switch the backend from using `@tensor` to `batched_gemm`. But I didn't check type stability.

Using generated function can solve this issue.

**Comment by GiggleLiu** [comment]
The gitlab CI fails, @under-Peter do you have any idea why it fails?

**Comment by under-Peter** [comment]
@GiggleLiu  the test seems to fail only due to errors in the coverage reporting where it says:
```
$ export CI_DISABLE_CURNN_TEST=true
 $ julia -e 'using Pkg; Pkg.add("Coverage")'
 /bin/bash: line 97: julia: command not found
 ERROR: Job failed: exit code 1
```
but not sure what that's about. Looking at the gitlab-CI, it's always been failing for at least the last two months. But right now, since it's only coverage, I wouldn't worry too much.

**Comment by GiggleLiu** [comment]
Thanks for reviewing, GPU tests pass on my laptop. I will merge it.

**Pull request merged**
